### ISSUE TITLE
Test failures with Python 3.13

### ISSUE THREAD

**Issue by emollier** [globus/globus-sdk-python#1056]
Hi,

As initially identified by Stefano Rivera in [Debian bug #1082219], a couple of tests in Globus SDK 3.45.0 are failing with Python 3.13.  Relevant part of the Debian bug report shows:
```
==================================== ERRORS ====================================
_ ERROR at setup of test_user_app_login_flow_manager_configuration[MockLoginFlowManager-MockLoginFlowManager] _

>       lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    )
E   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <sqlite3.Connection object at 0xffffa2ec7970>
E   
E   Traceback (most recent call last):
E     File "/usr/lib/python3.13/unittest/mock.py", line 2225, in __init__
E       def __init__(self, name, parent):
E       
E   ResourceWarning: unclosed database in <sqlite3.Connection object at 0xffffa2ec7970>

/usr/lib/python3/dist-packages/flaky/flaky_pytest_plugin.py:146: PytestUnraisableExceptionWarning
____________________ ERROR at setup of test_slash_join[a-b] ____________________

>       lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    )
E   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <sqlite3.Connection object at 0xffffa2282980>
E   
E   Traceback (most recent call last):
E     File "/usr/lib/python3.13/unittest/mock.py", line 2225, in __init__
E       def __init__(self, name, parent):
E       
E   ResourceWarning: unclosed database in <sqlite3.Connection object at 0xffffa2282980>

/usr/lib/python3/dist-packages/flaky/flaky_pytest_plugin.py:146: PytestUnraisableExceptionWarning
```

It is a bit unclear to me whether the problem would be in Globus SDK itself, or in the mock module (which I think was tested against version 5.1.0, but I'm not entirely confident).  In doubt, I thought you might like to be aware of the issue.

Have a nice day,  :)
Étienne.

[Debian bug #1082219]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082219

**Comment by emollier** [comment]
Please disregard my comment about the mock library, after some digging I realized it is part of the Python 3.13 unittest standard library.

**Comment by kurtmckee** [comment]
@emollier Thanks again for reporting this! This fix will be available as soon as we publish our next release.

**Comment by emollier** [comment]
Great, Thanks for tackling this so promptly!  :)
