### ISSUE TITLE
Paginated Calls Don't Error Until Iteration Time

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#19]
There's a somewhat unexpected/odd behavior that results from the way that Python handles iterator definition.

Consider the following simple example:
```python
>>> def err_iter():
...     raise ValueError()
...     for x in (1, 2):
...             yield x
... 
>>> xs = err_iter() # fine, but will error when we try to use it
>>> next(xs) # uh-oh!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in err_iter
ValueError
```

It's a bit of a subtlety of the way that iterator functions work -- it doesn't run at all until the first call to `next()` happens. That holds even if it will error before ever reaching the `yield`.

For paginated API calls, the behavior is unintuitive and confusing.
Even an unauthenticated call to instantiate the iterator will "work". It will just fail at iteration time.

It would be better to raise these errors at iteration instantiation time.
I think we can do that by attaching a little bit of state to the class instance in the PaginatedResource decorator.

**Comment by sirosen** [comment]
Solved by #20
