### ISSUE TITLE
ConsentRequired error

### ISSUE THREAD

**Issue by bpuchala** [globus/globus-sdk-python#924]
I have an application that implements a CLI interface for Globus transfers to [Materials Commons](https://materialscommons.org). Something has changed so that transfer attempts from `umich#greatlakes` result in errors like #638:

> 'ConsentRequired', 'Missing required data_access consent'

I've seen the examples [here](https://globus-sdk-python.readthedocs.io/en/stable/examples/minimal_transfer_script/index.html#best-effort-proactive-handling-of-consentrequired) but I'm not sure I understand the underlying issue.

Is this is change in Globus or the endpoint admin settings? Is it still possible to store a refresh token and reuse it without logging in each time? Or does this mean our users have to log in each time they do a transfer?

**Comment by derek-globus** [comment]
Hey Brian,

Globus is in the middle of a campaign requesting endpoint owners upgrade from GCSv4 to GCSv5 ([blog post](https://www.globus.org/blog/migrating-gcsv5)). `umich#greatlakes` has likely performed that upgrade which includes, among other features, a move from user certificates to OAuth-based authentication (where this `data_access` scope/consent originates).

It is still possible to store a refresh token and reuse it without having your users log in each time they transfer. You'll need to add the `data_access` scope as a dynamic dependency however for the mapped collection(s) being accessed. This requests of your users that they authorize your client to request transfers to/from a particular mapped collection.

Here's what that scope construction looks like using sdk constructs:

```python
mapped_collection_id = ...

# Construct default transfer:all scope
transfer_scope = globus_sdk.scopes.TransferScopes.all
# Construct a mapped collection's data_access scope
data_access_scope = globus_sdk.scopes.GCSCollectionScopeBuilder(mapped_collection_id).data_access
# Attach the data access scope to transfer a dynamic dependent scope
transfer_scope.add_dependency(data_access)
```

That scope can then be used in your existing oauth2 token grant request:

```python
auth_client.oauth2_start_flow(..., requested_scopes=transfer_scope)
```

**Comment by bpuchala** [comment]
I was getting type errors using the verbatim code above, so I'm using this now:
```
from globus_sdk.scopes import TransferScopes, GCSCollectionScopeBuilder
transfer_scope = TransferScopes.make_mutable("all")
if config.globus.endpoint_id:
    print("ADD data_access scope")
    data_access_scope = GCSCollectionScopeBuilder(
        config.globus.endpoint_id).make_mutable("data_access", optional=True)
    transfer_scope.add_dependency(data_access_scope)
```
But I'm still getting:

> 'ConsentRequired', 'Missing required data_access consent'

The complete test script I'm using looks like this:
```
import globus_sdk
from materials_commons.cli.user_config import Config

CLIENT_ID = '1e4aacbc-8c10-4812-a54a-8434d2030a41'

# reads a user's config file, which has both materials commons and globus info,
# including endpoint_id and refresh token if present at:
# config.globus.endpoint_id and config.globus.transfer_rt
config = Config()
# umich#greatlakes                                                                                                                                                  ## https://app.globus.org/file-manager/collections/454f457e-a41b-4807-8775-d132f15a228f/overview
# config.globus.endpoint_id = "454f457e-a41b-4807-8775-d132f15a228f"

# The Materials Commons Endpoint on NSDF-EP
# https://app.globus.org/file-manager/collections/0b2ada36-bf56-11ed-9614-4b6fcc022e5a/overview
materials_commons_endpoint_id = "0b2ada36-bf56-11ed-9614-4b6fcc022e5a"


if not config.globus.transfer_rt:
    client = globus_sdk.NativeAppAuthClient(CLIENT_ID)
    client.oauth2_start_flow(refresh_tokens=True)

    authorize_url = client.oauth2_get_authorize_url()
    try:
        import webbrowser
        webbrowser.open(authorize_url)
    except:
        pass

    print('Please login. If a webpage does not open automatically, go here:\n\n{0}\n\n'.format(authorize_url))
    auth_code = input('Please enter the code you get after login here: ').strip()
    token_response = client.oauth2_exchange_code_for_tokens(auth_code)

    globus_transfer_data = token_response.by_resource_server['transfer.api.globus.org']

    # save the token
    config.globus.transfer_rt = globus_transfer_data['refresh_token']
    config.globus.transfer_at = globus_transfer_data['access_token']
    config.globus.transfer_eas = globus_transfer_data['expires_at_seconds']
    config.save()


# use the refresh token
config = Config()

from globus_sdk.scopes import TransferScopes, GCSCollectionScopeBuilder
transfer_scope = TransferScopes.make_mutable("all")
if config.globus.endpoint_id:
    print("ADD data_access scope")
    data_access_scope = GCSCollectionScopeBuilder(
        config.globus.endpoint_id).make_mutable("data_access", optional=True)
    transfer_scope.add_dependency(data_access_scope)


client = globus_sdk.NativeAppAuthClient(CLIENT_ID)
client.oauth2_start_flow(refresh_tokens=True, requested_scopes=transfer_scope)


authorizer = globus_sdk.RefreshTokenAuthorizer(config.globus.transfer_rt, client)

# and try using `tc` to make TransferClient calls. Everything should just
# work -- for days and days, months and months, even years
tc = globus_sdk.TransferClient(authorizer=authorizer)


# Prepare a transfer
label = "test-globus-greatlakes-mc"
sync_level = "checksum"
tdata = globus_sdk.TransferData(
    tc,
    config.globus.endpoint_id,
    materials_commons_endpoint_id,
    label=label,
    sync_level=sync_level,
)

# Add files
local_abspath = "/home/bpuchala/test_greatlakes-2.txt"
destpath = "/__globus_uploads/dc8a8522-52ad-4394-a935-90d12058f30a/test_greatlakes-2.txt"
recursive = False
tdata.add_item(local_abspath, destpath, recursive=(recursive and os.path.isdir(local_abspath)))

# Submit transfer
transfer_result = tc.submit_transfer(tdata)
task_id = transfer_result["task_id"]

print("Globus task_id:", task_id)
```

With result:

> ADD data_access scope
Traceback (most recent call last):
  File "/home/bpuchala/test_upload.py", line 81, in <module>
    transfer_result = tc.submit_transfer(tdata)
  File "/home/bpuchala/<something>/python3.9/site-packages/globus_sdk/services/transfer/client.py", line 1522, in submit_transfer
    return self.post("/transfer", data=data)
  File "/home/bpuchala/<something>/python3.9/site-packages/globus_sdk/client.py", line 157, in post
    return self.request(
  File "/home/bpuchala/<something>/python3.9/site-packages/globus_sdk/client.py", line 312, in request
    raise self.error_class(r)
globus_sdk.services.transfer.errors.TransferAPIError: ('POST', 'https://transfer.api.globus.org/v0.10/transfer', 'Bearer', 403, 'ConsentRequired', 'Missing required data_access consent', 'xJzoxh2yU')

I can make the file transfer successfully using the Globus file manager website with those same endpoint ids.

**Comment by sirosen** [comment]
> I was getting type errors using the verbatim code above, so I'm using this now:
> ...

Yes, there is a minor error in Derek's code sample. He used `TransferScopes.all`, but it looks like you've already found that you need to use `TransferScopes.make_mutable("all")`.
(This is a bit of an interface wrinkle which we hope to resolve in the next major version of the SDK, but changing it carries compatibility concerns.)

I think a really good place for you to look for prior art is our example of proactive consent handling:
https://globus-sdk-python.readthedocs.io/en/stable/examples/minimal_transfer_script/index.html#best-effort-proactive-handling-of-consentrequired

----

There are two things in your script which I see as areas of concern.

1. Probable cause of the error: not completing the second login flow

I notice that you call `oauth2_start_flow()` but then do not perform a login flow afterwards. Doing so basically makes that call a no-op. `oauth2_start_flow()` creates in-memory state for handling a login flow, but it is only used if you follow the authorization link to Globus Auth and return with the auth_code.

Make sure you persist the resulting tokens back to your token storage after completing the login flow.
In our example scripts, we wrap login in a function so that it can easily be called with relevant parameters.

2. Risky assumptions around which endpoints require `data_access`

I see you unconditionally add a data_access scope for the configured endpoint ID.
It would be much safer to check if data_access is needed, ideally on both the source and destination endpoints.
That way, if a user of this script configures an endpoint which does or does not require the data_access consent, the script will remain the same.

-----

If you know which collections are going to be used a priori, you may be able to hardcode the use of a data_access scope. But if it's configurable and your code is meant to be generic, you need to have some check to determine whether or not it's necessary.

I recommend the `ls` check used in our example because it will have the correct behavior of succeeding if you are using a token with which you have already consented to a data_access scope.

**Comment by sirosen** [comment]
I hope that the references and info we provided were sufficient. I'm going to go ahead and close this.
Please feel free to reopen or reach us via `support@globus.org` if you're still having trouble.
